name: CI Pipeline - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-qa:
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      git_branch          : 'main'
      release_type        : 'major'
      target_deploy       : 'qa'
      should_increment_tag: true
      ui_folder           : 'mgraph_ai_service_html_graph__render_ui'
      ui_version          : 'v0/v0.2'
    secrets: inherit