name: CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      git_branch          : 'dev'
      release_type        : 'minor'
      target_deploy       : 'dev'
      should_increment_tag: true
      ui_folder           : 'mgraph_ai_service_html_graph__render_ui'
      ui_version          : "v0/v0.2"
    secrets: inherit